### ISSUE TITLE
Implement `IndexBuffer`

### ISSUE THREAD

**Issue by axel22** [storm-enroute/macrogl#26]
Currently the `BasicLighting` example uses index buffers by interacting with the OpenGL API directly.

**Comment by axel22** [comment]
@storm-enroute-bot

**Comment by PlayerWithoutName** [comment]
I hope you remember about this issue, i really need indexing

**Comment by axel22** [comment]
Sure, I'll hack something in the next few days, and it should become available in the snapshot version.

**Comment by axel22** [comment]
You might want to look at this commit for the initial version:

https://github.com/storm-enroute/macrogl/commit/c55cfc1bce866ea620a7b0c046e79709470589b5

**Comment by axel22** [comment]
After this commit:

https://github.com/storm-enroute/macrogl/commit/a2ecb708963075f8c2923023ba0fdfb23564bb2e

`IndexBuffer` provides this functionality:

https://github.com/storm-enroute/macrogl/blob/master/src/test/scala/org/macrogl/examples/BasicLighting.scala

Screenshot:

![capture](https://cloud.githubusercontent.com/assets/151774/10262197/6b961724-69bd-11e5-94bd-ba2c6c3040c7.PNG)
